../build/data.rel: data.c ../generated/tiles.h ../generated/player.h \
 ../generated/enemy.h ../generated/map.h ../generated/map2.h
../build/game.rel: game.c ../../../include/ubox.h ../../../include/spman.h \
 ../../../include/ubox.h ../../../include/mplayer.h ../../../include/ap.h \
 helpers.h main.h game.h ../generated/map.h ../generated/map2.h \
 ../generated/player.h ../generated/enemy.h
../build/helpers.rel: helpers.c ../../../include/ubox.h helpers.h
../build/main.rel: main.c ../../../include/ubox.h ../../../include/mplayer.h \
 helpers.h game.h main.h ../generated/tiles.h